title: x
description: xx
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: jmvh
repo_url: "https://github.com/jintaos2/Monto_Carlo_Path_Tracing"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
